import jsPDF from 'jspdf';

/**
 * PDF Export Utility for ZAP Generators
 * Matches Industry PDF format and structure
 */

interface PDFSection {
  title: string;
  content: string | string[];
}

interface PDFExportOptions {
  title: string;
  subtitle?: string;
  sections: PDFSection[];
  metadata?: {
    generatedDate?: string;
    productName?: string;
    generatorType?: string;
  };
}

/**
 * Export content to PDF with industry-standard formatting
 */
export function exportToPDF(options: PDFExportOptions): void {
  const { title, subtitle, sections, metadata } = options;
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  let yPosition = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  // Header - ZAP branding
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('ZAP', margin, yPosition);
  yPosition += 15;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(title, maxWidth);
  doc.text(titleLines, margin, yPosition);
  yPosition += titleLines.length * 8;

  // Subtitle
  if (subtitle) {
    yPosition += 5;
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    doc.setFont('helvetica', 'normal');
    const subtitleLines = doc.splitTextToSize(subtitle, maxWidth);
    doc.text(subtitleLines, margin, yPosition);
    yPosition += subtitleLines.length * 6;
  }

  // Metadata
  if (metadata) {
    yPosition += 5;
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    
    if (metadata.generatedDate) {
      doc.text(`Generated: ${metadata.generatedDate}`, margin, yPosition);
      yPosition += 5;
    }
    
    if (metadata.productName) {
      doc.text(`Product: ${metadata.productName}`, margin, yPosition);
      yPosition += 5;
    }
    
    if (metadata.generatorType) {
      doc.text(`Generator: ${metadata.generatorType}`, margin, yPosition);
      yPosition += 5;
    }
  }

  // Separator line
  yPosition += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Sections
  sections.forEach((section, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }

    // Section title
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    const sectionTitleLines = doc.splitTextToSize(section.title, maxWidth);
    doc.text(sectionTitleLines, margin, yPosition);
    yPosition += sectionTitleLines.length * 7 + 3;

    // Section content
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    doc.setFont('helvetica', 'normal');

    const content = Array.isArray(section.content) ? section.content : [section.content];
    
    content.forEach((item, itemIndex) => {
      // Check page break
      if (yPosition > pageHeight - 30) {
        doc.addPage();
        yPosition = 20;
      }

      const contentLines = doc.splitTextToSize(item, maxWidth - 5);
      
      // Add bullet point for arrays
      if (Array.isArray(section.content)) {
        doc.circle(margin + 2, yPosition - 1.5, 0.8, 'F');
        doc.text(contentLines, margin + 6, yPosition);
        yPosition += contentLines.length * 6 + 3;
      } else {
        doc.text(contentLines, margin, yPosition);
        yPosition += contentLines.length * 6;
      }
    });

    // Add spacing between sections
    yPosition += 8;
  });

  // Footer on last page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by ZAP',
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  }

  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${timestamp}.pdf`;

  // Save the PDF
  doc.save(filename);
}
