import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildConceptScriptPrompt } from "./conceptScriptGenerator";
import { validateScriptStructure } from "./_core/conceptScriptValidator";

/**
 * HOOK-WORDING HOLD-BACK (2026-09-27, COMPLETION_AND_FIRST_DEPLOY_PROPOSAL §2.2).
 *
 * The sprint 4 hook wording measured no improvement against the same-day control, so the first deploy ships
 * production's prompt, not the branch's. These tests pin that: the script prompt the held branch builds is
 * BYTE-IDENTICAL to what production (87596d7) builds for the same input, and the structure-retry sentence is
 * production's. The label-only hook check stays — it records a label and sends the model nothing.
 *
 * The fixture was generated by running 87596d7's own `buildConceptScriptPrompt` from a clean checkout. This test
 * failed against the branch before the restore (148 characters longer in every case), which is what shows it
 * can detect a difference.
 */
const fixture = JSON.parse(
  readFileSync(join(__dirname, "__fixtures__", "concept-script-prompt-87596d7.json"), "utf8"),
) as {
  cases: Array<{ name: string; concept: any; cascade: string; seconds: number; material: boolean; prompt: string }>;
};

describe("the script prompt is production's, byte for byte", () => {
  it("the fixture actually loaded (§15k)", () => {
    expect(fixture.cases.length).toBe(4);
    for (const c of fixture.cases) expect(c.prompt.length).toBeGreaterThan(9000);
  });

  for (const c of fixture.cases) {
    it(`identical to 87596d7 for: ${c.name}`, () => {
      expect(buildConceptScriptPrompt(c.concept, c.cascade, c.seconds, c.material)).toBe(c.prompt);
    });
  }
});

describe("the structure-retry sentence is production's", () => {
  // The exact tail 87596d7 (and 0288828^) sends on a structure retry, for these opts.
  const PRODUCTION_TAIL =
    'Regenerate the full script so: there are ≥3 scenes; every scene has a non-empty spokenLine; the FIRST scene is the hook; the top-level hookPattern is exactly "problem_first"; and total spoken words fit a 30-second read (~';

  it("a failing script's retry note carries production's sentence, and no hook-length instruction", () => {
    const r = validateScriptStructure(
      { hookPattern: "wrong_pattern", scenes: [{ sceneNumber: 1, sceneType: "hook", spokenLine: "Every Sunday at 6pm the dread arrives before Monday even does.", onScreenText: "X", deliveryNote: "d" }] } as any,
      { hookPattern: "problem_first", targetSeconds: 30 },
    );
    expect(r.ok).toBe(false);
    if (r.ok) return;
    expect(r.failContext).toContain(PRODUCTION_TAIL);
    expect(r.failContext).toContain("Keep it tight — this length runs clean across Reels, Stories and Feed.");
    expect(r.failContext).not.toMatch(/opening SENTENCE/i);
    // The label is still recorded — the check is kept, only the instruction is held back.
    expect(r.labels.some((h) => h.classId === "script_hook_too_long")).toBe(true);
  });
});
