import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { toast } from "sonner";
import { Flag, CheckCircle, XCircle, AlertTriangle } from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  resolved: "bg-green-100 text-green-700",
  dismissed: "bg-gray-100 text-gray-700",
};

const CONTENT_TYPE_LABELS: Record<string, string> = {
  headline: "Headline",
  hvco: "Free Opt-In",
  heroMechanism: "Hero Mechanism",
  icp: "Ideal Customer",
  adCopy: "Ad Copy",
  email: "Email Sequence",
  whatsapp: "WhatsApp Sequence",
  landingPage: "Landing Page",
  offer: "Sales Offer",
};

export default function AdminContentModeration() {
  const [statusFilter, setStatusFilter] = useState<"pending" | "resolved" | "dismissed" | "">("");
  const [resolveDialogFlag, setResolveDialogFlag] = useState<any>(null);
  const utils = trpc.useUtils();

  const { data: flags, isLoading } = trpc.admin.getFlaggedContent.useQuery({
    status: statusFilter || undefined,
  });

  const resolveFlag = trpc.admin.resolveFlaggedContent.useMutation({
    onSuccess: () => {
      toast.success("Flag resolved");
      setResolveDialogFlag(null);
      utils.admin.getFlaggedContent.invalidate();
    },
    onError: () => toast.error("Failed to resolve flag"),
  });

  const flagList: any[] = (flags as any[]) || [];

  return (
    <div className="space-y-6 max-w-5xl">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Flag className="h-6 w-6 text-primary" /> Content Moderation
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          Review flagged content generated by users. Resolve or dismiss each flag.
        </p>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-3 gap-4">
        {["pending", "resolved", "dismissed"].map((s) => {
          const count = flagList.filter((f) => f.status === s).length;
          return (
            <Card key={s} className="cursor-pointer hover:border-primary/50 transition-colors" onClick={() => setStatusFilter(s as any)}>
              <CardContent className="pt-4 pb-3">
                <p className="text-2xl font-bold">{count}</p>
                <p className="text-sm text-muted-foreground capitalize">{s}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Filter */}
      <div className="flex items-center gap-3">
        <Select value={statusFilter} onValueChange={(v) => setStatusFilter(v as any)}>
          <SelectTrigger className="w-44">
            <SelectValue placeholder="All statuses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">All statuses</SelectItem>
            <SelectItem value="pending">Pending</SelectItem>
            <SelectItem value="resolved">Resolved</SelectItem>
            <SelectItem value="dismissed">Dismissed</SelectItem>
          </SelectContent>
        </Select>
        {statusFilter && (
          <Button variant="ghost" size="sm" onClick={() => setStatusFilter("")}>Clear</Button>
        )}
      </div>

      {/* Flags list */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">
            {isLoading ? "Loading…" : `${flagList.length} flag${flagList.length !== 1 ? "s" : ""}`}
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="flex items-center justify-center h-32">
              <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-primary" />
            </div>
          ) : flagList.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Flag className="h-8 w-8 mx-auto mb-2 opacity-30" />
              <p>No flagged content found.</p>
            </div>
          ) : (
            <div className="divide-y">
              {flagList.map((flag: any) => (
                <div key={flag.id} className="px-4 py-3 flex items-start gap-4">
                  <AlertTriangle className="h-4 w-4 text-orange-500 mt-0.5 shrink-0" />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      <Badge className="text-xs">{CONTENT_TYPE_LABELS[flag.content_type] || flag.content_type}</Badge>
                      <Badge className={`text-xs ${STATUS_COLORS[flag.status]}`}>{flag.status}</Badge>
                      <span className="text-xs text-muted-foreground">ID #{flag.content_id}</span>
                    </div>
                    {flag.flag_reason && (
                      <p className="text-sm text-muted-foreground">{flag.flag_reason}</p>
                    )}
                    {flag.content_text && (
                      <p className="text-sm mt-1 bg-muted/40 rounded px-2 py-1 line-clamp-2">{flag.content_text}</p>
                    )}
                    <p className="text-xs text-muted-foreground mt-1">
                      Flagged {new Date(flag.created_at).toLocaleString()}
                      {flag.resolved_at && ` · Resolved ${new Date(flag.resolved_at).toLocaleString()}`}
                    </p>
                  </div>
                  {flag.status === "pending" && (
                    <div className="flex gap-2 shrink-0">
                      <Button
                        size="sm"
                        variant="outline"
                        className="text-green-600 border-green-200 hover:bg-green-50"
                        onClick={() => setResolveDialogFlag({ ...flag, action: "resolved" })}
                      >
                        <CheckCircle className="h-3.5 w-3.5 mr-1" /> Resolve
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="text-gray-600"
                        onClick={() => setResolveDialogFlag({ ...flag, action: "dismissed" })}
                      >
                        <XCircle className="h-3.5 w-3.5 mr-1" /> Dismiss
                      </Button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Resolve confirmation dialog */}
      <Dialog open={!!resolveDialogFlag} onOpenChange={() => setResolveDialogFlag(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {resolveDialogFlag?.action === "resolved" ? "Resolve Flag" : "Dismiss Flag"}
            </DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {resolveDialogFlag?.action === "resolved"
              ? "Mark this flag as resolved. The content will remain but the flag will be closed."
              : "Dismiss this flag. No action will be taken on the content."}
          </p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setResolveDialogFlag(null)}>Cancel</Button>
            <Button
              onClick={() => resolveFlag.mutate({ flagId: resolveDialogFlag.id, status: resolveDialogFlag.action })}
              disabled={resolveFlag.isPending}
            >
              {resolveFlag.isPending ? "Saving…" : "Confirm"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
